#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint
if [ $? -ne 0 ]; then
  echo "\n❌ Lint failed. Commit aborted."
  exit 1
fi
npm run test
if [ $? -ne 0 ]; then
  echo "\n❌ Unit tests failed. Commit aborted."
  exit 1
fi
